#
# This file is part of Edgehog.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.DeploymentCachingAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:application_deployments), :status, to: :state

    rename table(:application_deployments), :message, to: :last_message

    alter table(:application_deployments) do
      modify :last_message, :text
      modify :state, :text, null: true, default: nil
      add :resources_state, :text
    end
  end

  def down do
    alter table(:application_deployments) do
      remove :resources_state
      modify :status, :text, null: false, default: "created"
      modify :message, :text
    end

    rename table(:application_deployments), :last_message, to: :message

    rename table(:application_deployments), :state, to: :status
  end
end
