defmodule Edgehog.Repo.Migrations.DeploymentContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:application_deployments) do
      add :context, :text
    end
  end

  def down do
    alter table(:application_deployments) do
      remove :context
    end
  end
end
